accounts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('register/', views.register_page, name="register"),
    path("login/", views.login_page, name="login"),
    path("logout/", views.logout_request, name= "logout"),
]

coparentbot/urls.py
from django.urls import path
from . import views

app_name = 'coparentbot'

urlpatterns = [
    path('', views.whatsapp_demo, name='whatsapp_demo'),
    path('parenting-plan/', views.parenting_plan, name='parenting_plan'),
    path('visitation/', views.visitation, name='visitation'),
    path('change-request/', views.change_request, name='change_request'),
    path('conversation/', views.conversation, name='conversation'),
]

coparentbot_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from tastypie.api import Api
from coparentbot.api import ParentingPlanResource, VisitationResource, ChangeRequestResource, ConversationResource, ParentResource

v1_api = Api(api_name='v1')
v1_api.register(ParentingPlanResource())
v1_api.register(ParentResource())
v1_api.register(VisitationResource())
v1_api.register(ChangeRequestResource())
v1_api.register(ConversationResource())

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('api/', include(v1_api.urls)),
    path('', include('coparentbot.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %}
    </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'coparentbot:whatsapp_demo' %}">Co Parenting Bot</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
              
            {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'register' %}">Register</a>
            </li>
            {% endif %}
            
          </ul>
        </div>
      </nav>

    {% for message in messages %}
        <div class="container-fluid p-0">
            <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="True">&times;</span>
                </button>
                {{ message }}
            </div>
        </div>
    {% endfor %}
    
    <div class="container">
        {% block body %}{% endblock %}
    </div>

    <!-- Footer -->
    <footer>
        <div class="footer-top">
            <div class="container">
                <div class="row">
                    <div class="col-md-3 footer-about wow fadeInUp">
                        <h3>About</h3>
                        <p>
                           
                        </p>
                    </div>
                    <div class="col-md-4 offset-md-1 footer-contact wow fadeInDown">
                        <h3>Contact</h3>
                        <p><a href="https://github.com/kearabiloe">GitHub</a></p>
                        <p><a href=" www.linkedin.com/in/kearabiloe">LinkedIn</a></p>
                        <p>Email: <a href="mailto:kearabiloe.ledwaba@gmail.com">kearabiloe.ledwaba@gmail.com</a></p>
                    </div>
                    <div class="col-md-4 footer-links wow fadeInUp">
                        <div class="row">
                            <div class="col">
                                <h3>Useful Links</h3>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-bottom">
            <div class="container">
                <div class="row">
                       <div class="col footer-social">
                        <a href="#"><i class="fab fa-facebook-f"></i></a> 
                        <a href="#"><i class="fab fa-twitter"></i></a> 
                        <a href="#"><i class="fab fa-google-plus-g"></i></a> 
                        <a href="#"><i class="fab fa-instagram"></i></a> 
                        <a href="#"><i class="fab fa-pinterest"></i></a>
                    </div>
                   </div>
            </div>
        </div>
    </footer>
    
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    
    {% block js %}{% endblock %}

</body>
</html>